### ISSUE TITLE
Installing version 1.0.1 via docker plugin install return an error

### ISSUE THREAD

**Issue by BeOleg** [logzio/docker-logging-plugin#6]
```
root@test4:/mnt# docker plugin install store/logzio/logzio-logging-plugin:1.0.1 --alias logzio/logzio-logging-plugin
Error response from daemon: manifest for store/logzio/logzio-logging-plugin:1.0.1 not found: manifest unknown: manifest unknown
```

**Comment by skinderis** [comment]
I am also facing this issue. Maybe there is solution @idohalevi, as I see you are developing here?

**Comment by idohalevi** [comment]
@BeOleg @skinderis You're both right.
Apparently, the docker shop does not update automatically on new changes. I will try to update it and let you know

**Comment by idohalevi** [comment]
@BeOleg @skinderis Should work now

**Comment by BeOleg** [comment]
Thanks!

**Comment by BeOleg** [comment]
@idohalevi I have some more feedback for you if possible:

1. I did not find the version numbers on the log-shipping page in your web app, I had to Google the name of the plugin which brought me to GitHub (where there are also no releases, but the version numbers are stated at the bottom of the README.md).

2. Would it be possible to have some config to eliminate redundant logging on the plugin level?
Right now we get a lot of garbage logged 2000 times a minute by 3rd party libraries which makes it very difficult for us to get insights from the logs.

Shabat shalom!

@idohalevi 
@skinderis

**Comment by idohalevi** [comment]
@BeOleg That is some great feedback. I'll try to address this in the next week or two.

**Comment by idohalevi** [comment]
@BeOleg 
1) Docker store will not accept tags like `latest`. I think any way we should add a "change log" to the repo and it will also allow us to have better visibility of our versions

2) Sorry, it takes me time to address this, been busy with other projects. It will take me some time to implement it and I will mention you once it's merged

**Comment by idohalevi** [comment]
@BeOleg #9 should help with 2
